### ISSUE TITLE
Uncaught TypeError: treeView.serialize is not a function

### ISSUE THREAD

**Issue by piot** [davidpaulrosser/atom-glsl-preview#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [glsl-preview](https://github.com/amelierosser/atom-glsl-preview) package 0.13.0

### Stack Trace

Uncaught TypeError: treeView.serialize is not a function

```
At /Users/Peter/.atom/packages/glsl-preview/lib/main.coffee:116

TypeError: treeView.serialize is not a function
    at Object.updateTexture (/packages/glsl-preview/lib/main.coffee:116:26)
    at Object.addTexture (/packages/glsl-preview/lib/main.coffee:100:6)
    at /packages/glsl-preview/lib/main.coffee:49:6)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:45.3.0 glsl-preview:toggle (input.hidden-input)
     -0:57 core:confirm (input.hidden-input)
     -0:36.1.0 core:cancel (div.package-detail.panels-item)
     -0:30.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  4x -0:28.5.0 core:backspace (input.hidden-input)
     -0:26.6.0 editor:consolidate-selections (input.hidden-input)
     -0:26.6.0 core:cancel (input.hidden-input)
     -0:25.5.0 core:save (input.hidden-input)
     -0:24.9.0 intentions:highlight (input.hidden-input)
  2x -0:22.3.0 glsl-preview:toggle (input.hidden-input)
     -0:04.6.0 glsl-preview:addTexture (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.3 
atom-yeoman 0.3.15 
autocomplete-clang 0.11.3 
autocomplete-glsl 0.2.3 
busy-signal 1.4.3 
clang-format 1.29.0 
glsl-preview 0.13.0 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
language-glsl 2.0.1 
language-lisp 0.2.0 
linter 2.2.0 
linter-clang 4.1.1 
linter-gcc 0.7.1 
linter-glsl 2.1.3 
linter-ui-default 1.6.2 
lisp-paredit 0.5.5 
Parinfer 1.18.0 
rainbow-delimiters 1.3.0 
tabs-to-spaces 1.0.3 
xml-formatter 0.11.0 
```

**Comment by Garrettorious** [comment]
I received the same error. Simply made the example circle uv shader.

1. right click to add texture in tree view

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [glsl-preview](https://github.com/amelierosser/atom-glsl-preview) package 0.13.0


### Stack Trace

Uncaught TypeError: treeView.serialize is not a function

```
At C:\Users\garre\.atom\packages\glsl-preview\lib\main.coffee:116

TypeError: treeView.serialize is not a function
    at Object.updateTexture (/packages/glsl-preview/lib/main.coffee:116:26)
    at Object.addTexture (/packages/glsl-preview/lib/main.coffee:100:6)
    at /packages/glsl-preview/lib/main.coffee:49:6)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:49.6.0 glsl-preview:addTexture (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
glsl-preview 0.13.0 
language-glsl 2.0.1 
language-hlsl 1.2.0 
minimap 4.28.2 
Sublime-Style-Column-Selection 1.7.4 
unity-shader-files 0.3.1 
```

**Comment by fordhurley** [comment]
Googling the error turns up a few other packages that have a similar problem. Looks like something changed in the treeview package, but I haven't looked into it at all. These look like possible fixes to incorporate here:
- https://github.com/snowkit/atom-haxe/pull/69
- https://github.com/snowkit/atom-flow/pull/18
