### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by FormerlyM** [davidpaulrosser/atom-glsl-preview#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.4
**Thrown From**: [glsl-preview](https://github.com/fordhurley/atom-glsl-preview) package 1.4.2

### Stack Trace

Uncaught SyntaxError: Unexpected token import

```
At /usr/share/atom/resources/app/src/native-compile-cache.js:97

SyntaxError: Unexpected token import
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/glsl-preview/lib/glsl-preview-view.js:10:22)
    at /packages/glsl-preview/lib/glsl-preview-view.js:335:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at isGlslPreviewView (/packages/glsl-preview/lib/main.js:11:23)
    at Object.getActivePreview (/packages/glsl-preview/lib/main.js:85:9)
    at Object.toggle (/packages/glsl-preview/lib/main.js:63:26)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:09.6.0 glsl-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-glsl 0.2.3 
e2h-epitech-header 0.1.1 
file-icons 2.1.17 
glsl-preview 1.4.2 
go-plus 5.8.2 
latex 0.49.0 
multi-cursor 2.1.5 
```

**Comment by fordhurley** [comment]
Thanks for reporting this! Looks like I recently screwed up the way the shader-canvas dependency module is constructed, but it should be fixed now with the latest release (v1.4.4).
